"$schema" = 'https://starship.rs/config-schema.json'

format = '''
$username$directory$git_branch$cmd_duration
$conda$character
'''

add_newline = true

[username]
show_always = true

[character]
# success_symbol = '[➜](bold green)'
# error_symbol = '[✗](bold red) '

[conda]
# format = '[$symbol$environment]($style) '
format = '[$symbol$environment](dimmed green) '
ignore_base = false

[package]
# disabled = true
