"$schema" = 'https://starship.rs/config-schema.json'

format = '''
$username$hostname in $directory$git_branch$cmd_duration
$conda$character
'''

add_newline = true

[username]
show_always = true
format = '[$user]($style)'

[hostname]
format = '[@$hostname]($style)'

[character]
# success_symbol = '[➜](bold green)'
# error_symbol = '[✗](bold red) '

[conda]
format = '[$symbol$environment]($style) '
ignore_base = false

[package]
# disabled = true
