[[mgr.prepend_keymap]]
on = 'f'
run = 'plugin jump-to-char'

[[mgr.prepend_keymap]]
on = '<S-j>'
run = 'arrow 5'

[[mgr.prepend_keymap]]
on = '<S-k>'
run = 'arrow -5'

[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
