[mgr]
ratio = [1, 2, 3]
sort_by = "natural"

[preview]
max_width = 1920
max_height = 2160

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
  { run = 'nvim %*', block = true, for = "windows" },
]
open = [
  { run = 'open "$@"', for = "macos" },
  { run = 'start "" "%1"', orphan = true, for = "windows" },
]
reveal = [
  { run = 'open -R "$1"', for = "macos" },
  { run = 'explorer /select, "%1"', orphan = true, for = "windows" },
]

[[plugin.prepend_previewers]]
url = "*.csv"
run = 'faster-piper -- bat -p --color=always "$1"'

[[plugin.prepend_previewers]]
url = "*.md"
run = 'faster-piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dracula "$1"'

[[plugin.prepend_previewers]]
url = "*.tar"
run = 'faster-piper --format-url -- tar tf "$1"'

[[plugin.append_previewers]]
url = "*"
run = 'faster-piper -- hexyl --border=none --terminal-width=$w "$1"'
