# ╭───────────────────────────────────────────────╮
# │                   Pluygins                    │
# ╰───────────────────────────────────────────────╯

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "joshmedeski/tmux-nerd-font-window-name"

run "~/.tmux/plugins/tpm/tpm"


# ╭───────────────────────────────────────────────╮
# │                    Theme                      │
# ╰───────────────────────────────────────────────╯

# Base      #24273a
# Subface 0 #363a4f
# Text      #cad3f5
# Red       #ed8796
# Green     #a6da95
# Yellow    #eed49f
# Subtext 1 #b8c0e0

set -g status-position top

set -g status-bg "#24273a"
set -g status-fg "#cad3f5"

set -g status-left " "
set -g status-left-length 0

set -g window-status-style         "fg=#585b70"
set -g window-status-current-style "fg=#f9e2af"

set -g window-status-format         "#{?#{==:#I,1},󰬺 ,#{?#{==:#I,2},󰬻 ,#{?#{==:#I,3},󰬼 ,#{?#{==:#I,4},󰬽 ,#{?#{==:#I,5},󰬾 ,#{?#{==:#I,6},󰬿 ,#{?#{==:#I,7},󰭀 ,#{?#{==:#I,8},󰭁 ,#{?#{==:#I,9},󰭂 ,󰿩 }}}}}}}}}#W#{?window_zoomed_flag, 󰁌 , }"
set -g window-status-current-format "#{?#{==:#I,1},󰲡 ,#{?#{==:#I,2},󰲣 ,#{?#{==:#I,3},󰲥 ,#{?#{==:#I,4},󰲧 ,#{?#{==:#I,5},󰲩 ,#{?#{==:#I,6},󰲫 ,#{?#{==:#I,7},󰲭 ,#{?#{==:#I,8},󰲯 ,#{?#{==:#I,9},󰲱 ,󰿭 }}}}}}}}}#W#{?window_zoomed_flag, 󰁌 , }"

set -g  status-right "#[fg=#ed8796,bg=#24273a]🮉#[fg=#363a4f,bg=#ed8796] #[fg=#b8c0e0,bg=#24273a] #S  "
set -ag status-right "#[fg=#eed49f,bg=#24273a]🮉#[fg=#363a4f,bg=#eed49f] #[fg=#b8c0e0,bg=#24273a] #(whoami)  "
set -ag status-right "#[fg=#a6da95,bg=#24273a]🮉#[fg=#363a4f,bg=#a6da95] #[fg=#b8c0e0,bg=#24273a] #H "


# ╭───────────────────────────────────────────────╮
# │                    Options                    │
# ╰───────────────────────────────────────────────╯

# Set true color
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -sa terminal-features ",xterm-kitty:RGB"

set -g cursor-style bar
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g mode-keys vi
set-option -g allow-rename on
set -sg escape-time 50
set -sg repeat-time 0

# osc52
set -s set-clipboard on

# yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM


# ╭───────────────────────────────────────────────╮
# │                 Keybindings                   │
# ╰───────────────────────────────────────────────╯

unbind C-b
set -g prefix M-m
bind -n M-m send-prefix

# Visual mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi Y send -X copy-end-of-line

bind C-h swap-window -t -1\; select-window -t -1
bind C-l swap-window -t +1\; select-window -t +1

bind -n M-S-Up  select-pane -U
bind -n M-S-Down select-pane -D
bind -n M-S-Left  select-pane -L
bind -n M-S-Right select-pane -R

# Reload tmux.conf
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded."
